---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install java pacakage
    apt: 
      name: default-jdk
      state: latest

  - name : install nodejs
    apt:
      name: nodejs
      state: latest
