---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution_version == "CentOS"


  - name: remove java and node  pacakage
    apt: 
      name:
        -  default-jdk
        -  nodejs
        -  apache2
      state: absent

    when: ansible_distribution == "Ubuntu"
   
  - name : remove httpd 
    dnf:
      name: httpd
      state: absent

