---

- hosts: all
  become: true
  tasks:
    
 
  - name: install java nodejs and apache package for Ubuntu
    apt: 
      name:
        - default-jdk 
        - nodejs
        - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package for CentOS
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS" 
    


