---

- hosts: all
  become: true
  pre_tasks:
    
  - name: install update (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install java nodejs and apache package for Ubuntu
    tags: apache, apache2 , nodejs, java . ubuntu
    apt: 
      name:
        - default-jdk 
        - nodejs
        - apache2
      state: latest    
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package for CentOS
    tags: apache, centos, httpd
    yum:
      name:
        - httpd
        - php
      state: latest   
    when: ansible_distribution == "CentOS" 
    
- hosts: db_server
  become: true
  tasks:

  - name: install maria db(CentOS)
    tags:  centos, db, mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

