- name: install mariadb server package ( Centos )
  tags: centos, db, mariadb 
  yum: 
    name: mariadb
    state: latest
  when: ansible_distribution == "Centos"

- name: install mariadb server ( Ubuntu )
  tags: db, mariadb , ubuntu 
  apt: 
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
